FROM node:buster-slim

# |--------------------------------------------------------------------------
# | Common libraries and dependencies for conversion to img
# |--------------------------------------------------------------------------
RUN echo "deb http://httpredir.debian.org/debian/ buster main contrib non-free" > /etc/apt/sources.list &&\
    apt-get update &&\
    apt-get install -y curl wget gnupg ttf-mscorefonts-installer procps \
    && apt-get install -y imagemagick ghostscript poppler-utils

# |--------------------------------------------------------------------------
# This is due to a security vulnerability that has been addressed in Ghostscript 9.24 (source). 
# Make sure you have Ghostscript ≥9.24:
# gs --version
# If yes, just remove the whole following section from /etc/ImageMagick-6/policy.xml:
# <!-- disable ghostscript format types -->
# <policy domain="coder" rights="none" pattern="PS" />
# <policy domain="coder" rights="none" pattern="PS2" />
# <policy domain="coder" rights="none" pattern="PS3" />
# <policy domain="coder" rights="none" pattern="EPS" />
# <policy domain="coder" rights="none" pattern="PDF" />
# <policy domain="coder" rights="none" pattern="XPS" />


# For canvas
# sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev 

# |--------------------------------------------------------------------------
# | LibreOffice
# |--------------------------------------------------------------------------
# | https://github.com/nextcloud/docker/issues/380
RUN mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1 &&\ 
    echo "deb http://httpredir.debian.org/debian/ buster-backports main contrib non-free" >> /etc/apt/sources.list &&\
    apt-get update &&\
    apt-get -t buster-backports -y install libreoffice

# |--------------------------------------------------------------------------
# | Unoconv
# |--------------------------------------------------------------------------
ENV UNO_URL=https://raw.githubusercontent.com/dagwieers/unoconv/master/unoconv
RUN curl -Ls $UNO_URL -o /usr/bin/unoconv &&\
    chmod +x /usr/bin/unoconv &&\
    ln -s /usr/bin/python3 /usr/bin/python &&\
    unoconv --version

# |--------------------------------------------------------------------------
# | PDFtk
# |--------------------------------------------------------------------------
# |
# | Installs PDFtk as an alternative to pdfcpu for merging PDFs.
# | https://github.com/thecodingmachine/maestro/issues/29
# |
RUN apt-get -y install pdftk

RUN apt-get purge -y build-essential curl wget unzip git cmake && \
    apt-get autoremove -y --purge

# |--------------------------------------------------------------------------
# | Default user
# |--------------------------------------------------------------------------
ARG MAESTRO_USER_GID=1001
ARG MAESTRO_USER_UID=1001
RUN groupadd --gid ${MAESTRO_USER_GID} maestro \
    && useradd --uid ${MAESTRO_USER_UID} --gid maestro --shell /bin/bash --home /maestro --no-create-home maestro \
    && mkdir /maestro \
    && chown maestro: /maestro

# |--------------------------------------------------------------------------
# | Installs the app and sets up the port
# |--------------------------------------------------------------------------
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN npm install 
EXPOSE 3000

CMD ["npm", "run", "start"]
